services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupalpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
volumes:
  drupal_data:
  db_data: